project:
  type: website
  output-dir: docs

website:
  title: "Kendall Landwehr"
  favicon: "Quarto-photos/favicon.ico"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: Resume.qmd
      - text: Projects
        href: Projects.qmd
      
  page-footer:
    background: light
    left: "Copyright 2025, Kendall Landwehr"
    right: "This website is built with Quarto"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full
    include-in-header:
     - text: | 
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

editor: visual

