project:
  type: website
output-dir: docs

website:
  title: "Kendall Landwehr"
  favicon: "Quarto-photos/favicon.ico"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - Projects.qmd
      
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full


editor: visual

