project:
  type: website
output-dir: docs

website:
  title: "Kendall Landwehr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - Projects.qmd

#Supplying two theme options for users to toggle between
format:
  html:
    theme: 
      light: lumen
      dark: darkly 
    css: styles.css
    toc: true
    page-layout: full

editor: visual

