project:
  type: website
  output-dir: docs

website:
  title: "Kendall Landwehr"
  favicon: "Quarto-photos/favicon.ico"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: Resume.qmd
      - text: Projects
        href: Projects.qmd
      
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full


editor: visual

